version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven..."
      - mvn --version

  build:
    commands:
      - echo "Building Java Lambda Package..."
      - mvn clean package -DskipTests
      - ls -lh target/

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

post_build:
  commands:
    - echo "Uploading JAR file to S3..."
    - aws s3 cp target/*.jar s3://springbook-bucket/
    - echo "✅ Build & Upload completed successfully!"
